// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo4NxFrg5xWCfBNzeLD0ZVUADKatE4iMA',
    appId: '1:489509362219:android:b1f57cd6af90f13e04286e',
    messagingSenderId: '489509362219',
    projectId: 'chatme-f8dd8',
    storageBucket: 'chatme-f8dd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX-MQWr8QbXG3McP_-NFrqHdWm6VVD9Sk',
    appId: '1:489509362219:ios:e4c61a39b0123f0d04286e',
    messagingSenderId: '489509362219',
    projectId: 'chatme-f8dd8',
    storageBucket: 'chatme-f8dd8.appspot.com',
    androidClientId: '489509362219-dueio1dbv2eldfl1dt2h7vghpr2rrf8r.apps.googleusercontent.com',
    iosClientId: '489509362219-9srincj2t49ds61ni1idoigasvqo6mlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionApp',
  );
}
